In [280]:
import numpy as np
import pandas as pd

df = pd.read_csv('data/data.csv')
df.head()

       Width     Length  Result
0  34.623660  78.024693       0
1  30.286711  43.894998       0
2  35.847409  72.902198       0
3  60.182599  86.308552       1
4  79.032736  75.344376       1

In [281]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Width   100 non-null    float64
 1   Length  100 non-null    float64
 2   Result  100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [282]:
df.describe()

            Width      Length      Result
count  100.000000  100.000000  100.000000
mean    65.644274   66.221998    0.600000
std     19.458222   18.582783    0.492366
min     30.058822   30.603263    0.000000
25%     50.919511   48.179205    0.000000
50%     67.032988   67.682381    1.000000
75%     80.212529   79.360605    1.000000
max     99.827858   98.869436    1.000000

In [283]:
X = df[['Width', 'Length']]
X.shape

(100, 2)

In [284]:
# Standarize
mean = X.mean(axis = 0)
std = X.std(axis = 0)
X = (X - mean) / std
print(X)

       Width    Length
0  -1.594216  0.635141
1  -1.817101 -1.201489
2  -1.531325  0.359483
3  -0.280687  1.080923
4   0.688062  0.490905
..       ...       ...
95  0.917087 -0.960121
96 -1.201681  1.123720
97  1.730412  0.137407
98 -0.529558 -0.069422
99  0.469294  1.254269

[100 rows x 2 columns]

In [285]:
y = df['Result']
y.shape

(100,)

In [286]:
X = np.hstack([np.ones((len(X), 1)), X])
print(X.shape)

(100, 3)

In [287]:
n_features = X.shape[-1]
theta = np.random.rand(n_features)
print(theta)
print(theta.reshape(-1, 1).shape)

[0.79430815 0.76471117 0.88607994]
(3, 1)

In [288]:
def logistic_function(z):
    return 1 / (1 + np.exp(-z))

def predict(x, theta):
    z = np.dot(x, theta)
    y_hat = logistic_function(z)
    return y_hat
def compute_loss(y_hat, y):
    loss = sum(-1 * (y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))) / len(y)
    return loss

def compute_gradient(x, y_hat, y):
    gradient = np.dot(x.T, (y_hat - y)) / len(y)
    return gradient

def update_weight(theta, gradient, lr):
    theta = theta - lr * gradient
    return theta

In [289]:
epoch_max = 10
lr = 0.1
losses = []
for epoch in range(epoch_max):
    # for each epoch - n samples
    y_hat = predict(X, theta)

    loss = compute_loss(y_hat, y)

    losses.append(loss)

    gradient = compute_gradient(X, y_hat, y)

    theta = update_weight(theta, gradient, lr)
print(losses)

[0.3882948993300588, 0.38528587447507234, 0.3823759877542913, 0.37956079005191506, 0.3768360625304591, 0.37419780426945665, 0.37164222047951917, 0.3691657112863746, 0.3667648610748864, 0.36443642837949014]

In [290]:
print(theta)

[0.7512622  0.89670483 0.96968424]

In [292]:
y_preds = predict(X, theta)
y_preds[:5]

array([0.4844069 , 0.11474069, 0.43209733, 0.82458453, 0.86345333])

In [293]:
thresholds = [0.1, 0.45, 0.5, 0.55, 0.65, 0.7, 0.75, 0.8]
accs = []
for threshold in thresholds:
    y_pre_th = []
    for y_pred in y_preds:
        if y_pred >= threshold:
            y_pre_th.append(1)
        else:
            y_pre_th.append(0)
    y_pred_th = np.asarray(y_pre_th)
    acc = sum(y_pre_th == y) / len(y)
    accs.append(acc)
accs

[0.6, 0.85, 0.92, 0.92, 0.87, 0.84, 0.78, 0.74]